<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5289" started-at="2022-09-27T07:00:12Z" finished-at="2022-09-27T07:00:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5289" started-at="2022-09-27T07:00:12Z" finished-at="2022-09-27T07:00:17Z">
      <class name="LoginModule.Nametc2_Test">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:LoginModule.Nametc2_Test@48140564]" name="launchBrowser" is-config="true" duration-ms="2034" started-at="2022-09-27T12:30:10Z" finished-at="2022-09-27T12:30:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="navigateToApplication()[pri:0, instance:LoginModule.Nametc2_Test@48140564]" name="navigateToApplication" is-config="true" duration-ms="5211" started-at="2022-09-27T12:30:12Z" finished-at="2022-09-27T12:30:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToApplication -->
        <test-method status="SKIP" signature="checkWithDifferentData(java.lang.String)[pri:0, instance:LoginModule.Nametc2_Test@48140564]" name="checkWithDifferentData" duration-ms="0" started-at="2022-09-27T12:30:17Z" data-provider="testdata" finished-at="2022-09-27T12:30:17Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: .\src\test\resources\testdata\testdata.xlsx.xlsx (The process cannot access the file because it is being used by another process)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: .\src\test\resources\testdata\testdata.xlsx.xlsx (The process cannot access the file because it is being used by another process)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.io.FileNotFoundException: .\src\test\resources\testdata\testdata.xlsx.xlsx (The process cannot access the file because it is being used by another process)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at org.apache.poi.poifs.nio.FileBackedDataSource.newSrcFile(FileBackedDataSource.java:161)
	at org.apache.poi.poifs.nio.FileBackedDataSource.<init>(FileBackedDataSource.java:64)
	at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:219)
	at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:167)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:254)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:226)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:205)
	at GenericUtility.ReadExcel.readMultipleData(ReadExcel.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkWithDifferentData -->
        <test-method status="PASS" signature="logoutFromApplication()[pri:0, instance:LoginModule.Nametc2_Test@48140564]" name="logoutFromApplication" is-config="true" duration-ms="1" started-at="2022-09-27T12:30:17Z" finished-at="2022-09-27T12:30:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method status="PASS" signature="teardownTheBrowser()[pri:0, instance:LoginModule.Nametc2_Test@48140564]" name="teardownTheBrowser" is-config="true" duration-ms="778" started-at="2022-09-27T12:30:18Z" finished-at="2022-09-27T12:30:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownTheBrowser -->
      </class> <!-- LoginModule.Nametc2_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
